server {
    listen 80;

    # Admin App
    location /admin {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

    # Candidate App
    location /candidate {
        alias /usr/share/nginx/html/candidate/;
        try_files $uri $uri/ /candidate/index.html;
    }

    # Redirect root to admin for convenience
    location / {
        return 301 /admin;
    }
}
